#
###################################
# Site wide configuration
####################################
#
title: thechargedneutron - webpage
email:
description: My personal webpage.
url: # the base hostname & protocol for your site
keywords: ["blog", "jekyll"]

#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Paris
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
permalink:         /articles/:year-:month/:title

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Kumar Ashutosh
  avatar: webpage_dp.jpg
  job: "Student"
  bio: "i code. i debug. i code."
  quote: "क्रांति की ज्वाला जलती रहनी चाहिए!"
  email: kumar.ashutosh.ee[AT]gmail.com
  disqus-shortname:
  twitter: chargedneutron_
  facebook: kumarashutosh0
  google:
    plus: #username
    analytics:
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: thechargedneutron
  gitlab: #username
  stackoverflow: 7841612/thechargedneutron #123456/username   from a "http://stackoverflow.com/users/123456/username" link
  linkedin: kumar-ashutosh-07
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
  reddit: #username
  telegram: #username

#
#####################
# Plugins
#####################
#
plugins:
  - jekyll-analytics

#
#####################
# Google analytics
#####################
#
jekyll_analytics:
  GoogleAnalytics:          # Add, if you want to track with Google Analytics
    id: UA-180283382-1          # Required - replace with your tracking id
    anonymizeIp: false      # Optional - Default: false - set to true for anonymized tracking
